name:                ringell
version:             0.1.0.0
github:              "mayconamaro/ringell"
license:             BSD3
author:              "Maycon Amaro"
maintainer:          "maycon.amaro97@gmail.com"
copyright:           "2022 Maycon Amaro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Compiler from general to terminating programs 
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ringell#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.4.0

library:
  source-dirs: src

executables:
  ringell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    #- -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - ringell

tests:
  ringell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ringell
    - random >= 1.2.0
    - QuickCheck >= 2.14.2
